[features]
seeds = false
[programs.localnet]
tic_tac_toe = "2Vp6DmE6YL9ffS8bb215YbWS6jBBWtADpmpXFYbx2eRv"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/hoon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.anchor.test.json -t 0 tests/Tic-tac-toe.ts"
